name: Website - Deploy to AWS S3

concurrency:
  group: deploy-website-${{ github.ref_name }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - demo
      - prod
      - dev
    paths:
      - "src/**"
      - "blog/**"
      - "static/**"
      - "docusaurus.config.ts"
      - "sidebars.ts"

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: write # This is required for actions/checkout
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build
        env:
          APP_URL: ${{ vars.APP_URL }}

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          # Delete all old unused files in the bucket
          args: --delete
        env:
          SOURCE_DIR: build/
          AWS_S3_BUCKET: instasdr-${{ github.ref_name }}-website
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
